TARGET = embox
ARCH = x86

// For MAC OS X
//CROSS_COMPILE = i386-elf-

CFLAGS += -O0 -gdwarf-2
//CFLAGS += -fsanitize=undefined
CFLAGS += -m32
CFLAGS += -mno-mmx -mno-sse -mno-sse2 -mno-sse3

CXXFLAGS += -O0 -gdwarf-2
//CXXFLAGS += -fsanitize=undefined
CXXFLAGS += -m32
CXXFLAGS += -mno-mmx -mno-sse -mno-sse2 -mno-sse3
CXXFLAGS += -Wno-error=undef
CXXFLAGS += -fno-exceptions
CXXFLAGS += -fno-rtti

LDFLAGS += -m elf_i386
